const fs=require('node:fs');const path=require('node:path');
const root=path.join(__dirname,'..'),out=path.join(root,'dist');
const labels={'consulting-agency':'Consultoría','digital-agency':'Agencia digital','real-estate':'Inmobiliaria','education-platform':'Educación','health-wellness':'Bienestar','saas-product':'Producto SaaS','tech-startup':'Startup','saas-avanzado':'SaaS avanzado','ecommerce-premium':'Comercio electrónico','fitness-app':'Fitness'};
const featured=['consulting-agency','digital-agency','real-estate'];
fs.rmSync(out,{recursive:true,force:true});fs.mkdirSync(out);fs.cpSync(path.join(root,'public'),path.join(out,'assets'),{recursive:true});
const contact=slug=>'mailto:contact@alicelabs.site?subject='+encodeURIComponent('Adaptación de diseño: '+(labels[slug]||'proyecto web'))+'&body='+encodeURIComponent('Quiero solicitar una propuesta de adaptación.\nDiseño: '+(slug||'por definir')+'\nMi negocio:\nObjetivo de la página:\nContenido disponible:\nFecha deseada:\n');
for(const [slug,label]of Object.entries(labels)){
 const dest=path.join(out,slug),src=path.join(root,'landing-pages',slug);fs.mkdirSync(dest);
 let html=fs.readFileSync(path.join(src,'index.html'),'utf8');
 const partial=!/<\/html>/i.test(html);
 if(partial){const end=html.lastIndexOf('</section>');if(end<0)throw new Error('No complete sections: '+slug);html=html.slice(0,end+10)+'</body></html>';}

 html=html.replace(/<script\b[^>]*>[\s\S]*?<\/script\s*>/gi,'').replace(/\s+on\w+\s*=\s*(?:"[^"]*"|'[^']*'|[^\s>]+)/gi,'').replace(/javascript:/gi,'disabled:');
 // No example links can send visitors to a fictitious checkout, phone or inbox.
 html=html.replace(/href\s*=\s*(["'])(.*?)\1/gi,(all,q,value)=>{if(value.startsWith('#')||value==='style.css'||/^(https?:)?\/\//.test(value)&&/\.(css)(\?|$)/.test(value)||value.includes('fonts.googleapis.com'))return all;return `href=${q}#alicelabs-demo${q}`;});
 html=html.replace('</head>','<meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="../assets/demo.css"></head>');
 html=html.replace(/<body[^>]*>/i,match=>match+`<aside class="alicelabs-demo" id="alicelabs-demo" aria-label="Aviso de demostración"><p><strong>DEMO DE DISEÑO · ${label}${partial?' · Referencia parcial':''}</strong><br>Marcas, precios, testimonios y cifras son ejemplos ficticios. No hay compras, reservas ni envíos de formularios.</p><a href="../">Volver al catálogo</a><a href="${contact(slug)}">Solicitar adaptación por correo</a></aside>`).replace('</body>','<script src="../assets/demo.js" defer></script></body>');
 html=html.replace(/<(input|textarea|select|button)\b/gi,'<$1 disabled').replace(/<form\b[^>]*>/gi,'<form><fieldset disabled><legend>Formulario de muestra desactivado; no introduzcas datos personales.</legend>').replace(/<\/form>/gi,'</fieldset></form>');
 const ids=new Set([...html.matchAll(/\bid=["']([^"']+)["']/g)].map(m=>m[1]));
 html=html.replace(/href=(["'])#([^"']*)\1/g,(all,q,id)=>ids.has(id)?all:`href=${q}#alicelabs-demo${q}`);
 fs.writeFileSync(path.join(dest,'index.html'),html);fs.copyFileSync(path.join(src,'style.css'),path.join(dest,'style.css'));
}
const descriptions={'consulting-agency':'Presenta servicios profesionales y una propuesta clara de contacto.','digital-agency':'Organiza especialidades, proceso y una muestra de trabajos aprobados.','real-estate':'Presenta una agencia y propiedades autorizadas, sin inventario ni reservas automáticas.'};
const cards=featured.map((slug,i)=>`<article class="card"><span class="tag">0${i+1} / Diseño adaptable</span><h2>${labels[slug]}</h2><p>${descriptions[slug]}</p><a class="button" href="${slug}/">Explorar diseño</a></article>`).join('');
fs.writeFileSync(path.join(out,'index.html'),`<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Proyectos web a medida | AliceLabs</title><meta name="description" content="Tres puntos de partida para adaptar una web comercial a tu negocio. Explora diseños y solicita una propuesta con alcance definido."><link rel="stylesheet" href="assets/catalog.css"></head><body><header><a href="./">AliceLabs / Proyectos web</a><a href="#alcance">Qué incluye la adaptación</a></header><main><span class="tag">Del diseño a tu negocio</span><h1>Adaptamos una web a lo que necesitas vender.</h1><p class="intro">Elige un punto de partida. Definimos contigo el contenido, el contacto y la entrega. Estos diseños muestran posibilidades visuales; no son negocios en funcionamiento.</p><a class="button" href="${contact('')}">Solicitar una propuesta</a><p>Se abrirá un borrador en tu aplicación de correo. No se envía automáticamente.</p><section aria-label="Diseños destacados" class="grid">${cards}</section><section id="alcance" class="scope"><span class="tag">Una entrega concreta</span><h2>Diseño, contenido y publicación acordados.</h2><p>La propuesta puede incluir adaptación de marca, contenido proporcionado por el cliente, diseño móvil, enlaces de contacto y código editable. Páginas, revisiones, precio y fecha se acuerdan por escrito antes de empezar.</p><p>Pagos, CRM, inventario, cuentas de usuario, scraping y analítica requieren implementación y presupuesto propios. Dominio y hosting se detallan aparte. No garantizamos ventas ni posicionamiento.</p></section><section class="scope"><h2>Más referencias de diseño</h2><p>Son ejemplos de presentación. Las funciones de negocio y los controles interactivos no están implementados.</p><div class="list">${Object.entries(labels).filter(([s])=>!featured.includes(s)).map(([s,l])=>`<a href="${s}/">${l}</a>`).join('')}</div></section><section class="scope"><h2>Cuéntanos qué necesitas.</h2><p>Incluye tu actividad, el objetivo de la página y el contenido que ya tienes. Responderemos al correo que envíes para preparar el alcance.</p><a class="button" href="${contact('')}">Preparar solicitud por correo</a></section></main><footer>Catálogo AliceLabs. Las demos contienen contenido ficticio y no procesan datos de clientes.</footer></body></html>`);
fs.writeFileSync(path.join(out,'catalog.json'),JSON.stringify(Object.entries(labels).map(([slug,label])=>({slug,label,status:'design_demo',featured:featured.includes(slug)})),null,2));
console.log('Built commercial catalogue and 10 explicitly non-operational design demos.');
